# [[file:xo-tools.note::*cargo][cargo:1]]
[package]
name = "xo-tools"
version = "0.0.3"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
pager = "0.15"
regex = "1"
structopt = "0.2"
quicli = "0.4"

[dev-dependencies]
# cargo:1 ends here
